version: 1
update_configs:
  - package_manager: 'java:gradle'
    directory: '/'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:minor"
